"""initial_schema

Revision ID: 828a5c39ed8b
Revises: 
Create Date: 2026-03-21 14:46:15.674528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '828a5c39ed8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profesores_activo', table_name='profesores', schema='admin', postgresql_where='(activo = true)')
    op.drop_index('idx_profesores_usuario', table_name='profesores', schema='admin')
    op.drop_table('profesores', schema='admin')
    op.drop_table('logs_auditoria_2027_04', schema='audit')
    op.drop_index('idx_profest_estado', table_name='profesor_estudiantes', schema='admin')
    op.drop_index('idx_profest_estudiante', table_name='profesor_estudiantes', schema='admin')
    op.drop_index('idx_profest_profesor', table_name='profesor_estudiantes', schema='admin')
    op.drop_table('profesor_estudiantes', schema='admin')
    op.drop_table('logs_auditoria_2026_08', schema='audit')
    op.drop_index('idx_log_2026_07_usuario', table_name='logs_auditoria_2026_07', schema='audit')
    op.drop_table('logs_auditoria_2026_07', schema='audit')
    op.drop_index('idx_obs_estudiante', table_name='observaciones_sesion', schema='admin')
    op.drop_index('idx_obs_sesion', table_name='observaciones_sesion', schema='admin')
    op.drop_table('observaciones_sesion', schema='admin')
    op.drop_index('idx_materias_codigo', table_name='materias', schema='admin')
    op.drop_table('materias', schema='admin')
    op.drop_index('idx_sesiones_activa', table_name='sesiones_auth', schema='admin')
    op.drop_index('idx_sesiones_token', table_name='sesiones_auth', schema='admin')
    op.drop_index('idx_sesiones_usuario', table_name='sesiones_auth', schema='admin')
    op.drop_table('sesiones_auth', schema='admin')
    op.drop_table('logs_auditoria_2026_11', schema='audit')
    op.drop_index('idx_tareas_completada', table_name='tareas_asignadas', schema='admin', postgresql_where='(completada = false)')
    op.drop_index('idx_tareas_profesor', table_name='tareas_asignadas', schema='admin')
    op.drop_table('tareas_asignadas', schema='admin')
    op.drop_table('logs_auditoria', schema='audit')
    op.drop_index('idx_config_clave', table_name='configuracion_sistema', schema='admin')
    op.drop_table('configuracion_sistema', schema='admin')
    op.drop_index('idx_sesiones_clase_estudiante', table_name='sesiones_clase', schema='admin')
    op.drop_index('idx_sesiones_clase_fecha', table_name='sesiones_clase', schema='admin')
    op.drop_index('idx_sesiones_clase_profesor', table_name='sesiones_clase', schema='admin')
    op.drop_table('sesiones_clase', schema='admin')
    op.drop_table('logs_auditoria_2026_09', schema='audit')
    op.drop_index('idx_log_2026_06_usuario', table_name='logs_auditoria_2026_06', schema='audit')
    op.drop_table('logs_auditoria_2026_06', schema='audit')
    op.drop_index('idx_log_2026_03_accion', table_name='logs_auditoria_2026_03', schema='audit')
    op.drop_index('idx_log_2026_03_usuario', table_name='logs_auditoria_2026_03', schema='audit')
    op.drop_table('logs_auditoria_2026_03', schema='audit')
    op.drop_table('logs_auditoria_2027_05', schema='audit')
    op.drop_table('logs_auditoria_2026_12', schema='audit')
    op.drop_table('logs_auditoria_2027_02', schema='audit')
    op.drop_index('idx_log_2026_05_usuario', table_name='logs_auditoria_2026_05', schema='audit')
    op.drop_table('logs_auditoria_2026_05', schema='audit')
    op.drop_index('idx_log_2026_04_usuario', table_name='logs_auditoria_2026_04', schema='audit')
    op.drop_table('logs_auditoria_2026_04', schema='audit')
    op.drop_table('logs_auditoria_2027_01', schema='audit')
    op.drop_table('logs_auditoria_2027_06', schema='audit')
    op.drop_table('logs_auditoria_2026_10', schema='audit')
    op.drop_table('logs_auditoria_2027_03', schema='audit')
    op.alter_column('estudiantes', 'id_estudiante',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='admin')
    op.drop_index('idx_estudiantes_apellido', table_name='estudiantes', schema='admin')
    op.drop_index('idx_estudiantes_codigo', table_name='estudiantes', schema='admin')
    op.drop_index('idx_estudiantes_deleted', table_name='estudiantes', schema='admin', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_estudiantes_documento', table_name='estudiantes', schema='admin')
    op.drop_index('idx_estudiantes_estado', table_name='estudiantes', schema='admin')
    op.drop_constraint('uq_estudiantes_documento', 'estudiantes', schema='admin', type_='unique')
    op.drop_constraint('estudiantes_created_by_fkey', 'estudiantes', schema='admin', type_='foreignkey')
    op.drop_table_comment(
        'estudiantes',
        existing_comment='Estudiantes matriculados. ~90 activos. Gestionado por mÃ³dulo admin.',
        schema='admin'
    )
    op.drop_column('estudiantes', 'alergias', schema='admin')
    op.drop_column('estudiantes', 'foto_perfil_url', schema='admin')
    op.drop_column('estudiantes', 'motivo_retiro', schema='admin')
    op.drop_column('estudiantes', 'created_by', schema='admin')
    op.drop_column('estudiantes', 'notas_medicas', schema='admin')
    op.drop_column('estudiantes', 'observaciones_gen', schema='admin')
    op.alter_column('usuarios', 'id_usuario',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='admin')
    op.drop_index('idx_usuarios_activo', table_name='usuarios', schema='admin', postgresql_where='(activo = true)')
    op.drop_index('idx_usuarios_deleted', table_name='usuarios', schema='admin', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_usuarios_email', table_name='usuarios', schema='admin')
    op.drop_index('idx_usuarios_rol', table_name='usuarios', schema='admin')
    op.drop_constraint('usuarios_created_by_fkey', 'usuarios', schema='admin', type_='foreignkey')
    op.drop_column('usuarios', 'foto_perfil_url', schema='admin')
    op.drop_column('usuarios', 'token_recuperacion', schema='admin')
    op.drop_column('usuarios', 'token_exp', schema='admin')
    op.drop_column('usuarios', 'created_by', schema='admin')
    op.drop_column('usuarios', 'telefono', schema='admin')
    op.drop_index('idx_errors_job', table_name='processing_errors', schema='audit')
    op.drop_index('idx_errors_stage', table_name='processing_errors', schema='audit')
    op.alter_column('bulletins', 'id_bulletin',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='processing')
    op.alter_column('bulletins', 'puntaje_combinado',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='65% Ã— puntaje_cuantitativo + 35% Ã— puntaje_cualitativo.',
               existing_nullable=True,
               schema='processing')
    op.drop_index('idx_bulletins_pending', table_name='bulletins', schema='processing', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index('idx_bulletins_result', table_name='bulletins', schema='processing')
    op.drop_index('idx_bulletins_status', table_name='bulletins', schema='processing')
    op.drop_table_comment(
        'bulletins',
        existing_comment='Boletines PDF. Un boletÃ\xadn por resultado. 3 bloques: cuantitativo, cualitativo, combinado 65/35.',
        schema='processing'
    )
    op.alter_column('observaciones_cualitativas', 'id_observacion',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='processing')
    op.drop_index('idx_obs_cual_result', table_name='observaciones_cualitativas', schema='processing')
    op.drop_table_comment(
        'observaciones_cualitativas',
        existing_comment='Formulario cualitativo completado por el orientador. respuestas.fuente indica si el valor viene del OCR o del orientador. respuestas.corregido=true cuando el orientador modificÃ³ un valor capturado automÃ¡ticamente.',
        schema='processing'
    )
    op.alter_column('processing_jobs', 'id_job',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='processing')
    op.alter_column('processing_jobs', 'file_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ruta temporal del video. Se pone NULL despuÃ©s de procesar (video eliminado del disco).',
               existing_nullable=True,
               schema='processing')
    op.alter_column('processing_jobs', 'file_hash',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='MD5 del archivo. Permite detectar uploads duplicados ya procesados (status=done).',
               existing_nullable=False,
               schema='processing')
    op.drop_index('idx_jobs_estudiante', table_name='processing_jobs', schema='processing')
    op.drop_index('idx_jobs_hash', table_name='processing_jobs', schema='processing')
    op.drop_index('idx_jobs_prospecto', table_name='processing_jobs', schema='processing')
    op.drop_index('idx_jobs_status', table_name='processing_jobs', schema='processing')
    op.drop_index('idx_jobs_template', table_name='processing_jobs', schema='processing')
    op.drop_table_comment(
        'processing_jobs',
        existing_comment='Cola de procesamiento. XOR: id_estudiante XOR id_prospecto siempre lleno.',
        schema='processing'
    )
    op.alter_column('prospectos', 'id_prospecto',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='processing')
    op.drop_index('idx_prospectos_fecha', table_name='prospectos', schema='processing')
    op.drop_index('idx_prospectos_nombre', table_name='prospectos', schema='processing')
    op.drop_table_comment(
        'prospectos',
        existing_comment='Registro liviano de personas NO matriculadas que realizan una prueba diagnÃ³stica. Si se matriculan despuÃ©s, el compaÃ±ero crea su registro en admin.estudiantes.',
        schema='processing'
    )
    op.alter_column('qualitative_results', 'id_qualitative',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='processing')
    op.alter_column('qualitative_results', 'gaze_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('NULL'),
               comment=None,
               existing_comment='NULL hasta confirmar compatibilidad hardware Samsung Galaxy S6 con grabaciÃ³n PIP.',
               existing_nullable=True,
               schema='processing')
    op.drop_index('idx_qual_job', table_name='qualitative_results', schema='processing')
    op.drop_table_comment(
        'qualitative_results',
        existing_comment='SeÃ±ales automÃ¡ticas extraÃ\xaddas del video y audio. Alimenta prefills del formulario. auto_captured_flags lista las mÃ©tricas que el sistema captÃ³: esas NO aparecen en el formulario.',
        schema='processing'
    )
    op.alter_column('test_results', 'id_result',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False,
               schema='processing')
    op.alter_column('test_results', 'ws',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Work Sheet leÃ\xaddo por OCR del frame de resumen de Class Navi.',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'study_time_min',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Study Time del resumen Class Navi (tiempo real del estudiante).',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'target_time_min',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Target Time del resumen Class Navi (TPT del nivel).',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'semaforo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='verde=sube nivel | amarillo=mantiene | rojo=refuerza.',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'raw_ocr_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Texto crudo extraÃ\xaddo por EasyOCR del frame de resumen para auditorÃ\xada.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.drop_index('idx_results_estudiante', table_name='test_results', schema='processing')
    op.drop_index('idx_results_job', table_name='test_results', schema='processing')
    op.drop_index('idx_results_prospecto', table_name='test_results', schema='processing')
    op.drop_index('idx_results_review', table_name='test_results', schema='processing', postgresql_where='(needs_manual_review = true)')
    op.drop_index('idx_results_semaforo', table_name='test_results', schema='processing')
    op.drop_table_comment(
        'test_results',
        existing_comment='Resultados cuantitativos extraÃ\xaddos del frame de resumen de Class Navi.',
        schema='processing'
    )
    op.alter_column('test_templates', 'answer_key',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Clave de respuestas: {"1":"3","2":"4",...}. No se usa para calcular score (lo hace Class Navi), sÃ\xad para referencia.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_templates', 'level_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='SemÃ¡foro por rangos: {verde:{min,max,punto_partida}, amarillo:{...}, rojo:{...}}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_templates', 'extraction_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='GuÃ\xada OCR: {key_frames:[0,25,50,75,100], secciones:[{id,inicio_pct,fin_pct}], buscar_en_video:bool}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_templates', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Metadatos del seed: {version, fuente, notas}. La versiÃ³n controla el upsert idempotente.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.drop_index('idx_templates_active', table_name='test_templates', schema='processing', postgresql_where='(active = true)')
    op.drop_index('idx_templates_code', table_name='test_templates', schema='processing')
    op.drop_index('idx_templates_subject', table_name='test_templates', schema='processing')
    op.drop_table_comment(
        'test_templates',
        existing_comment='29 plantillas de tests Kumon: 12 MAT, 12 ESP, 5 ING.',
        schema='processing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'test_templates',
        '29 plantillas de tests Kumon: 12 MAT, 12 ESP, 5 ING.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_templates_subject', 'test_templates', ['subject'], unique=False, schema='processing')
    op.create_index('idx_templates_code', 'test_templates', ['code'], unique=False, schema='processing')
    op.create_index('idx_templates_active', 'test_templates', ['active'], unique=False, schema='processing', postgresql_where='(active = true)')
    op.alter_column('test_templates', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Metadatos del seed: {version, fuente, notas}. La versiÃ³n controla el upsert idempotente.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_templates', 'extraction_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='GuÃ\xada OCR: {key_frames:[0,25,50,75,100], secciones:[{id,inicio_pct,fin_pct}], buscar_en_video:bool}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_templates', 'level_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='SemÃ¡foro por rangos: {verde:{min,max,punto_partida}, amarillo:{...}, rojo:{...}}',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_templates', 'answer_key',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Clave de respuestas: {"1":"3","2":"4",...}. No se usa para calcular score (lo hace Class Navi), sÃ\xad para referencia.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.create_table_comment(
        'test_results',
        'Resultados cuantitativos extraÃ\xaddos del frame de resumen de Class Navi.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_results_semaforo', 'test_results', ['semaforo'], unique=False, schema='processing')
    op.create_index('idx_results_review', 'test_results', ['needs_manual_review'], unique=False, schema='processing', postgresql_where='(needs_manual_review = true)')
    op.create_index('idx_results_prospecto', 'test_results', ['id_prospecto'], unique=False, schema='processing')
    op.create_index('idx_results_job', 'test_results', ['id_job'], unique=False, schema='processing')
    op.create_index('idx_results_estudiante', 'test_results', ['id_estudiante', sa.text('test_date DESC')], unique=False, schema='processing')
    op.alter_column('test_results', 'raw_ocr_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Texto crudo extraÃ\xaddo por EasyOCR del frame de resumen para auditorÃ\xada.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='processing')
    op.alter_column('test_results', 'semaforo',
               existing_type=sa.VARCHAR(length=10),
               comment='verde=sube nivel | amarillo=mantiene | rojo=refuerza.',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'target_time_min',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Target Time del resumen Class Navi (TPT del nivel).',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'study_time_min',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Study Time del resumen Class Navi (tiempo real del estudiante).',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'ws',
               existing_type=sa.VARCHAR(length=20),
               comment='Work Sheet leÃ\xaddo por OCR del frame de resumen de Class Navi.',
               existing_nullable=True,
               schema='processing')
    op.alter_column('test_results', 'id_result',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='processing')
    op.create_table_comment(
        'qualitative_results',
        'SeÃ±ales automÃ¡ticas extraÃ\xaddas del video y audio. Alimenta prefills del formulario. auto_captured_flags lista las mÃ©tricas que el sistema captÃ³: esas NO aparecen en el formulario.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_qual_job', 'qualitative_results', ['id_job'], unique=False, schema='processing')
    op.alter_column('qualitative_results', 'gaze_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='NULL hasta confirmar compatibilidad hardware Samsung Galaxy S6 con grabaciÃ³n PIP.',
               existing_nullable=True,
               schema='processing')
    op.alter_column('qualitative_results', 'id_qualitative',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='processing')
    op.create_table_comment(
        'prospectos',
        'Registro liviano de personas NO matriculadas que realizan una prueba diagnÃ³stica. Si se matriculan despuÃ©s, el compaÃ±ero crea su registro en admin.estudiantes.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_prospectos_nombre', 'prospectos', ['nombre_completo'], unique=False, schema='processing')
    op.create_index('idx_prospectos_fecha', 'prospectos', ['fecha_prueba'], unique=False, schema='processing')
    op.alter_column('prospectos', 'id_prospecto',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='processing')
    op.create_table_comment(
        'processing_jobs',
        'Cola de procesamiento. XOR: id_estudiante XOR id_prospecto siempre lleno.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_jobs_template', 'processing_jobs', ['id_template'], unique=False, schema='processing')
    op.create_index('idx_jobs_status', 'processing_jobs', ['status', sa.text('created_at DESC')], unique=False, schema='processing')
    op.create_index('idx_jobs_prospecto', 'processing_jobs', ['id_prospecto'], unique=False, schema='processing')
    op.create_index('idx_jobs_hash', 'processing_jobs', ['file_hash'], unique=False, schema='processing')
    op.create_index('idx_jobs_estudiante', 'processing_jobs', ['id_estudiante'], unique=False, schema='processing')
    op.alter_column('processing_jobs', 'file_hash',
               existing_type=sa.VARCHAR(length=32),
               comment='MD5 del archivo. Permite detectar uploads duplicados ya procesados (status=done).',
               existing_nullable=False,
               schema='processing')
    op.alter_column('processing_jobs', 'file_path',
               existing_type=sa.TEXT(),
               comment='Ruta temporal del video. Se pone NULL despuÃ©s de procesar (video eliminado del disco).',
               existing_nullable=True,
               schema='processing')
    op.alter_column('processing_jobs', 'id_job',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='processing')
    op.create_table_comment(
        'observaciones_cualitativas',
        'Formulario cualitativo completado por el orientador. respuestas.fuente indica si el valor viene del OCR o del orientador. respuestas.corregido=true cuando el orientador modificÃ³ un valor capturado automÃ¡ticamente.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_obs_cual_result', 'observaciones_cualitativas', ['id_result'], unique=False, schema='processing')
    op.alter_column('observaciones_cualitativas', 'id_observacion',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='processing')
    op.create_table_comment(
        'bulletins',
        'Boletines PDF. Un boletÃ\xadn por resultado. 3 bloques: cuantitativo, cualitativo, combinado 65/35.',
        existing_comment=None,
        schema='processing'
    )
    op.create_index('idx_bulletins_status', 'bulletins', ['status'], unique=False, schema='processing')
    op.create_index('idx_bulletins_result', 'bulletins', ['id_result'], unique=False, schema='processing')
    op.create_index('idx_bulletins_pending', 'bulletins', ['status'], unique=False, schema='processing', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('bulletins', 'puntaje_combinado',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='65% Ã— puntaje_cuantitativo + 35% Ã— puntaje_cualitativo.',
               existing_nullable=True,
               schema='processing')
    op.alter_column('bulletins', 'id_bulletin',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False,
               schema='processing')
    op.create_index('idx_errors_stage', 'processing_errors', ['stage'], unique=False, schema='audit')
    op.create_index('idx_errors_job', 'processing_errors', ['id_job'], unique=False, schema='audit')
    op.add_column('usuarios', sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True), schema='admin')
    op.add_column('usuarios', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('usuarios', sa.Column('token_exp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='admin')
    op.add_column('usuarios', sa.Column('token_recuperacion', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='admin')
    op.add_column('usuarios', sa.Column('foto_perfil_url', sa.TEXT(), autoincrement=False, nullable=True), schema='admin')
    op.create_foreign_key('usuarios_created_by_fkey', 'usuarios', 'usuarios', ['created_by'], ['id_usuario'], source_schema='admin', referent_schema='admin')
    op.create_index('idx_usuarios_rol', 'usuarios', ['id_rol'], unique=False, schema='admin')
    op.create_index('idx_usuarios_email', 'usuarios', ['email'], unique=False, schema='admin')
    op.create_index('idx_usuarios_deleted', 'usuarios', ['deleted_at'], unique=False, schema='admin', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_usuarios_activo', 'usuarios', ['activo'], unique=False, schema='admin', postgresql_where='(activo = true)')
    op.alter_column('usuarios', 'id_usuario',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='admin')
    op.add_column('estudiantes', sa.Column('observaciones_gen', sa.TEXT(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('estudiantes', sa.Column('notas_medicas', sa.TEXT(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('estudiantes', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('estudiantes', sa.Column('motivo_retiro', sa.TEXT(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('estudiantes', sa.Column('foto_perfil_url', sa.TEXT(), autoincrement=False, nullable=True), schema='admin')
    op.add_column('estudiantes', sa.Column('alergias', sa.TEXT(), autoincrement=False, nullable=True), schema='admin')
    op.create_table_comment(
        'estudiantes',
        'Estudiantes matriculados. ~90 activos. Gestionado por mÃ³dulo admin.',
        existing_comment=None,
        schema='admin'
    )
    op.create_foreign_key('estudiantes_created_by_fkey', 'estudiantes', 'usuarios', ['created_by'], ['id_usuario'], source_schema='admin', referent_schema='admin')
    op.create_unique_constraint('uq_estudiantes_documento', 'estudiantes', ['tipo_documento', 'numero_documento'], schema='admin')
    op.create_index('idx_estudiantes_estado', 'estudiantes', ['estado'], unique=False, schema='admin')
    op.create_index('idx_estudiantes_documento', 'estudiantes', ['tipo_documento', 'numero_documento'], unique=False, schema='admin')
    op.create_index('idx_estudiantes_deleted', 'estudiantes', ['deleted_at'], unique=False, schema='admin', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_estudiantes_codigo', 'estudiantes', ['codigo_estudiante'], unique=False, schema='admin')
    op.create_index('idx_estudiantes_apellido', 'estudiantes', ['primer_apellido'], unique=False, schema='admin')
    op.alter_column('estudiantes', 'id_estudiante',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False,
               schema='admin')
    op.create_table('logs_auditoria_2027_03',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2026_10',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2027_06',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2027_01',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2026_04',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_index('idx_log_2026_04_usuario', 'logs_auditoria_2026_04', ['id_usuario', sa.text('created_at DESC')], unique=False, schema='audit')
    op.create_table('logs_auditoria_2026_05',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_index('idx_log_2026_05_usuario', 'logs_auditoria_2026_05', ['id_usuario', sa.text('created_at DESC')], unique=False, schema='audit')
    op.create_table('logs_auditoria_2027_02',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2026_12',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2027_05',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('logs_auditoria_2026_03',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_index('idx_log_2026_03_usuario', 'logs_auditoria_2026_03', ['id_usuario', sa.text('created_at DESC')], unique=False, schema='audit')
    op.create_index('idx_log_2026_03_accion', 'logs_auditoria_2026_03', ['accion', sa.text('created_at DESC')], unique=False, schema='audit')
    op.create_table('logs_auditoria_2026_06',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_index('idx_log_2026_06_usuario', 'logs_auditoria_2026_06', ['id_usuario', sa.text('created_at DESC')], unique=False, schema='audit')
    op.create_table('logs_auditoria_2026_09',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('sesiones_clase',
    sa.Column('id_sesion', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('id_profesor', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_estudiante', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_materia', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nivel_trabajado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_sesion', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hora_fin', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('duracion_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado_sesion', sa.VARCHAR(length=20), server_default=sa.text("'en_curso'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado_sesion::text = ANY (ARRAY['en_curso'::character varying, 'completada'::character varying, 'cancelada'::character varying]::text[])", name='sesiones_clase_estado_sesion_check'),
    sa.CheckConstraint('hora_fin IS NULL OR hora_fin > hora_inicio', name='chk_sesion_horas'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['admin.estudiantes.id_estudiante'], name='sesiones_clase_id_estudiante_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_materia'], ['admin.materias.id_materia'], name='sesiones_clase_id_materia_fkey'),
    sa.ForeignKeyConstraint(['id_profesor'], ['admin.profesores.id_profesor'], name='sesiones_clase_id_profesor_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_sesion', name='sesiones_clase_pkey'),
    schema='admin',
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_sesiones_clase_profesor', 'sesiones_clase', ['id_profesor'], unique=False, schema='admin')
    op.create_index('idx_sesiones_clase_fecha', 'sesiones_clase', ['fecha_sesion'], unique=False, schema='admin')
    op.create_index('idx_sesiones_clase_estudiante', 'sesiones_clase', ['id_estudiante'], unique=False, schema='admin')
    op.create_table('configuracion_sistema',
    sa.Column('id_config', sa.INTEGER(), server_default=sa.text("nextval('admin.configuracion_sistema_id_config_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo_dato', sa.VARCHAR(length=30), server_default=sa.text("'string'::character varying"), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('editable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('sensible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("tipo_dato::text = ANY (ARRAY['string'::character varying, 'integer'::character varying, 'float'::character varying, 'boolean'::character varying, 'json'::character varying, 'date'::character varying]::text[])", name='configuracion_sistema_tipo_dato_check'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin.usuarios.id_usuario'], name='configuracion_sistema_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id_config', name='configuracion_sistema_pkey'),
    sa.UniqueConstraint('clave', name='configuracion_sistema_clave_key'),
    schema='admin'
    )
    op.create_index('idx_config_clave', 'configuracion_sistema', ['clave'], unique=False, schema='admin')
    op.create_table('logs_auditoria',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit',
    comment='AuditorÃ\xada completa del sistema. Particionada por mes.'
    )
    op.create_table('tareas_asignadas',
    sa.Column('id_tarea', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('id_profesor', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_estudiante', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('asignada_por', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_asignacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_limite', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completada', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('fecha_completada', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notificado_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('fecha_notificacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('observacion_profesor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prioridad', sa.VARCHAR(length=20), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("prioridad::text = ANY (ARRAY['baja'::character varying, 'normal'::character varying, 'alta'::character varying, 'urgente'::character varying]::text[])", name='tareas_asignadas_prioridad_check'),
    sa.CheckConstraint('completada = false OR completada = true AND fecha_completada IS NOT NULL', name='chk_tarea_completada'),
    sa.ForeignKeyConstraint(['asignada_por'], ['admin.usuarios.id_usuario'], name='tareas_asignadas_asignada_por_fkey'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['admin.estudiantes.id_estudiante'], name='tareas_asignadas_id_estudiante_fkey'),
    sa.ForeignKeyConstraint(['id_profesor'], ['admin.profesores.id_profesor'], name='tareas_asignadas_id_profesor_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_tarea', name='tareas_asignadas_pkey'),
    schema='admin'
    )
    op.create_index('idx_tareas_profesor', 'tareas_asignadas', ['id_profesor'], unique=False, schema='admin')
    op.create_index('idx_tareas_completada', 'tareas_asignadas', ['completada'], unique=False, schema='admin', postgresql_where='(completada = false)')
    op.create_table('logs_auditoria_2026_11',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('sesiones_auth',
    sa.Column('id_sesion', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='sesiones_auth_id_usuario_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion', name='sesiones_auth_pkey'),
    sa.UniqueConstraint('refresh_token', name='sesiones_auth_refresh_token_key'),
    schema='admin'
    )
    op.create_index('idx_sesiones_usuario', 'sesiones_auth', ['id_usuario'], unique=False, schema='admin')
    op.create_index('idx_sesiones_token', 'sesiones_auth', ['refresh_token'], unique=False, schema='admin')
    op.create_index('idx_sesiones_activa', 'sesiones_auth', ['activa', 'expires_at'], unique=False, schema='admin')
    op.create_table('materias',
    sa.Column('id_materia', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('codigo_materia', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('niveles_disponibles', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False),
    sa.Column('color_calendario', sa.VARCHAR(length=7), server_default=sa.text("'#3498db'::character varying"), autoincrement=False, nullable=False),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_materia', name='materias_pkey'),
    sa.UniqueConstraint('codigo_materia', name='materias_codigo_materia_key'),
    schema='admin',
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_materias_codigo', 'materias', ['codigo_materia'], unique=False, schema='admin')
    op.create_table('observaciones_sesion',
    sa.Column('id_observacion', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('id_sesion', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_profesor', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_estudiante', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('postura', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('agarre_lapiz', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('concentracion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('actitud', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nivel_frustracion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('observacion_libre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('visible_para_admin', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("actitud::text = ANY (ARRAY['positiva'::character varying, 'neutral'::character varying, 'negativa'::character varying]::text[])", name='observaciones_sesion_actitud_check'),
    sa.CheckConstraint("agarre_lapiz::text = ANY (ARRAY['correcto'::character varying, 'mejorable'::character varying, 'incorrecto'::character varying]::text[])", name='observaciones_sesion_agarre_lapiz_check'),
    sa.CheckConstraint("concentracion::text = ANY (ARRAY['alta'::character varying, 'media'::character varying, 'baja'::character varying]::text[])", name='observaciones_sesion_concentracion_check'),
    sa.CheckConstraint("nivel_frustracion::text = ANY (ARRAY['ninguno'::character varying, 'leve'::character varying, 'moderado'::character varying, 'alto'::character varying]::text[])", name='observaciones_sesion_nivel_frustracion_check'),
    sa.CheckConstraint("postura::text = ANY (ARRAY['correcta'::character varying, 'mejorable'::character varying, 'incorrecta'::character varying]::text[])", name='observaciones_sesion_postura_check'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['admin.estudiantes.id_estudiante'], name='observaciones_sesion_id_estudiante_fkey'),
    sa.ForeignKeyConstraint(['id_profesor'], ['admin.profesores.id_profesor'], name='observaciones_sesion_id_profesor_fkey'),
    sa.ForeignKeyConstraint(['id_sesion'], ['admin.sesiones_clase.id_sesion'], name='observaciones_sesion_id_sesion_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_observacion', name='observaciones_sesion_pkey'),
    schema='admin'
    )
    op.create_index('idx_obs_sesion', 'observaciones_sesion', ['id_sesion'], unique=False, schema='admin')
    op.create_index('idx_obs_estudiante', 'observaciones_sesion', ['id_estudiante'], unique=False, schema='admin')
    op.create_table('logs_auditoria_2026_07',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_index('idx_log_2026_07_usuario', 'logs_auditoria_2026_07', ['id_usuario', sa.text('created_at DESC')], unique=False, schema='audit')
    op.create_table('logs_auditoria_2026_08',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('profesor_estudiantes',
    sa.Column('id_asignacion', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('id_profesor', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_estudiante', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_materia', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nivel_actual', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_asignacion', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado::text = ANY (ARRAY['activo'::character varying, 'finalizado'::character varying, 'suspendido'::character varying]::text[])", name='profesor_estudiantes_estado_check'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_asignacion', name='chk_profest_fecha'),
    sa.ForeignKeyConstraint(['created_by'], ['admin.usuarios.id_usuario'], name='profesor_estudiantes_created_by_fkey'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['admin.estudiantes.id_estudiante'], name='profesor_estudiantes_id_estudiante_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_materia'], ['admin.materias.id_materia'], name='profesor_estudiantes_id_materia_fkey'),
    sa.ForeignKeyConstraint(['id_profesor'], ['admin.profesores.id_profesor'], name='profesor_estudiantes_id_profesor_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_asignacion', name='profesor_estudiantes_pkey'),
    sa.UniqueConstraint('id_profesor', 'id_estudiante', 'id_materia', name='uq_prof_est_materia'),
    schema='admin'
    )
    op.create_index('idx_profest_profesor', 'profesor_estudiantes', ['id_profesor'], unique=False, schema='admin')
    op.create_index('idx_profest_estudiante', 'profesor_estudiantes', ['id_estudiante'], unique=False, schema='admin')
    op.create_index('idx_profest_estado', 'profesor_estudiantes', ['estado'], unique=False, schema='admin')
    op.create_table('logs_auditoria_2027_04',
    sa.Column('id_log', sa.BIGINT(), server_default=sa.text("nextval('audit.logs_auditoria_id_log_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nombre_usuario', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rol_usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accion', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id_registro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', sa.VARCHAR(length=20), server_default=sa.text("'exito'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mensaje_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metodo_http', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('codigo_respuesta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duracion_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("metodo_http::text = ANY (ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying]::text[])", name='logs_auditoria_metodo_http_check'),
    sa.CheckConstraint("resultado::text = ANY (ARRAY['exito'::character varying, 'error'::character varying, 'advertencia'::character varying, 'bloqueado'::character varying]::text[])", name='logs_auditoria_resultado_check'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='logs_auditoria_id_usuario_fkey'),
    schema='audit'
    )
    op.create_table('profesores',
    sa.Column('id_profesor', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('numero_empleado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('especialidad', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('fecha_ingreso', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_retiro', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tipo_contrato', sa.VARCHAR(length=50), server_default=sa.text("'tiempo_completo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("tipo_contrato::text = ANY (ARRAY['tiempo_completo'::character varying, 'medio_tiempo'::character varying, 'hora_catedra'::character varying, 'contratista'::character varying]::text[])", name='chk_tipo_contrato'),
    sa.CheckConstraint('fecha_retiro IS NULL OR fecha_retiro >= fecha_ingreso', name='chk_profesores_retiro'),
    sa.ForeignKeyConstraint(['id_usuario'], ['admin.usuarios.id_usuario'], name='profesores_id_usuario_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_profesor', name='profesores_pkey'),
    sa.UniqueConstraint('id_usuario', name='profesores_id_usuario_key'),
    sa.UniqueConstraint('numero_empleado', name='profesores_numero_empleado_key'),
    schema='admin'
    )
    op.create_index('idx_profesores_usuario', 'profesores', ['id_usuario'], unique=False, schema='admin')
    op.create_index('idx_profesores_activo', 'profesores', ['activo'], unique=False, schema='admin', postgresql_where='(activo = true)')
    # ### end Alembic commands ###
